# Setup
# description:         'Абланатханалба.'
description:         'ABRACADABRA'
title:               '«abreg ad habra»'
url:                 ''
baseurl:             ''
# paginate:            5
#paginate_path: "/slovar/words/page:num"
markdown: kramdown
highlighter: rouge
# Permalinks
permalink: /:title/
# permalink:        pretty
paginate: 5
paginate_path: "/blog/:num/"

gems:
- jekyll-paginate

# About/contact
author:
  name:              Alyonka Chornaya
  url:               http://alyonka.black
  email:             a.chornaya@gmail.com
# Contact and social media links
# twitter: pawelgrzybek
# github: blackgirl
# facebook: grzybecki
# instagram: pawelgrzybek
# linkedin: pgrzybek

# Gems
# gems: [ 'jekyll-archives']
# Custom vars
version:             1.0.0
plugins_dir:            "/_plugins"
exclude: ['Gemfile']

# Pages
pages:       
  WTF: '/about'
  Archive: '/archive'
  Cловарь: '/slovar'
  Бложек: '/blog'
  Feed: '/atom.xml'

#collections
# collections:
#   astro:
#     title: 'Астрология'

# Custom vars