# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Black Hole
tagline:             'Black hole of sense'
description:         'The gravity on content with a hidden sense.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Alyonka Chornaya
  url:               http://alyonka.black
  email:             a.chornaya@gmail.com

# Custom vars
version:             1.0.0
