#Gems
# gems: [jekyll-paginate]
# Setup
description:         'Абланатханалба'
title:               '«abreg ad habra»'
url:                 ''
baseurl:             ''
# paginate:            5

# About/contact
author:
  name:              Alyonka Chornaya
  url:               http://alyonka.black
  email:             a.chornaya@gmail.com

# Custom vars
version:             1.0.0
